config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :categories
  devise_for :users

  resources :users, only: [:show, :index, :destroy] do
    member do
      get :assign_roles
      patch :update_roles
    end
  end

  root "home#index"

  resources :roles
  resources :comments, only: [:create, :destroy]

  post "toggle_like", to:  "likes#toggle_like", as: :toggle_like
  post "toggle_favorite", to:  "favorites#toggle_favorite", as: :toggle_favorites

  post "follow", to: 'follows#follow', as: :follow
  delete 'unfollow', to: 'follows#unfollow', as: :unfollow
  delete 'cancel_request', to: 'follows#cancel_request', as: :cancel_request

  post 'accept_follow', to: 'follows#accept_follow', as: :accept_follow
  delete 'decline_follow', to: 'follows#decline_follow', as: :decline_follow
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many_attached :images
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :preparation_steps, presence: true, length: { minimum: 10, maximum: 300 }
  validates :images, presence: true, blob: { content_type: :image }

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  load_and_authorize_resource

  def index
    redirect_to root_path
    @recipe = Recipe.new
    # @recipes = Recipe.all
    @categories = Category.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @categories = Category.all
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { redirect_to root_path, status: :unprocessable_entity, alert: @recipe.errors.full_messages }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to root_path, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { redirect_to root_path, status: :unprocessable_entity, alert: @recipe.errors.full_messages }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :description, :preparation_steps, :user_id, :category_id, :allow_comments,
                                   :show_likes_count, images: [])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_comment_post.html.erb
<%= turbo_frame_tag "recipe#{recipe.id}comments" do %>
  <%= form_with url: comments_path, method: :recipe, data: {controller: "comments", action: "turbo:submit-end->comments#clear"} do |f| %>
    <div class="card-footer d-flex justify-content-between bg-white">
      <%= f.hidden_field :recipe_id, value: recipe.id %>
      <%= f.text_area :comment_body, class: "w-75", placeholder: "Add a comment...", style:"border:none" %>
      <%= f.submit "Post", class: "text-primary fw-bold", style: "background:none;border:none"  %>
    </div>
  <% end %>
<% end %>

app/views/recipes/_edit_form.html.erb
<div class="modal fade modal-lg" id="staticBackdropEdit" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <%= form_with(model: recipe, url: recipe_path(recipe), local: true) do |form| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Edit Recipe</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="my-2">
            <% if current_user.profile_pic.attached? %>
              <%= image_tag current_user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 10%" %>
            <% else %>
              <%= image_tag 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 10%" %>
            <% end %>
            <span class="fw-bold mx-2"><%= current_user.username.capitalize %></span>
          </div>
          <div class="my-2">
            <%= form.text_field :title, placeholder: "Write a title...", class: "form-control" %>
          </div>
          <div class="my-2">
            <%= form.text_area :description, placeholder: "Add description", class: "form-control" %>
          </div>
          <div class="my-2">
            <%= form.text_area :preparation_steps, placeholder: "Add preparation steps", class: "form-control" %>
          </div>
          <div class="my-2">
            <%= form.select :category_id, options_for_select(@categories.map { |category| [category.name, category.id] }), { prompt: "Select Category" }, class: "form-select text-muted" %>
          </div>
          <div class="d-flex justify-content-between align-items-center border form-control my-2" data-bs-toggle="collapse" href="#collapseExample<%= recipe.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
            <a class="text-dark" style="text-decoration: none;">Advanced Settings</a>
            <i class="fa-solid fa-chevron-down"></i>
          </div>
          <div class="collapse" id="collapseExample<%= recipe.id %>">
            <div class="card card-body">
              <div class="form-check form-switch">
                <%= form.check_box :allow_comments, class: "form-check-input", role: "switch", checked: true %>
                <%= form.label :allow_comments, style: "display: block", class: "form-check-label" %>
              </div>
              <div class="form-check form-switch">
                <%= form.check_box :show_likes_count, class: "form-check-input", role: "switch", checked: true %>
                <%= form.label :show_likes_count, style: "display: block", class: "form-check-label" %>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= form.submit "Update Recipe", class: "btn btn-orange" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_form.html.erb
<!-- Modal -->
<div class="modal fade modal-lg" id="staticBackdrop<%= recipe.id %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <%= form_with(model: recipe, url: recipe.persisted? ? recipe_path(recipe) : recipes_path) do |form| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Create New Recipe</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="d-flex">
            <div class="border-end border-secondary mx-2 px-2" style="width: 50%;">
              <%= render "layouts/shared/errors" , obj: @recipe%>
              <div class="my-2">
                <% if current_user.profile_pic.attached? %>
                  <%= image_tag current_user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 10%" %>
                <% else %>
                  <%= image_tag 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 10%" %>
                <% end %>
                <span class="fw-bold mx-2"><%= (current_user.username).capitalize %></span>
              </div>
              <div class="my-2">
                <%= form.text_field :title, placeholder: "Write a title...", class: "form-control" %>
              </div>
              <div class="my-2">
                <%= form.text_area :description, placeholder: "Add description", class: "form-control" %>
              </div>
              <div class="my-2">
                <%= form.text_area :preparation_steps, placeholder: "Add preparation steps", class: "form-control" %>
              </div>
              <div class="my-2">
                <%= form.select :category_id, options_for_select(@categories.map { |category| [category.name, category.id] }), { prompt: "Select Category" }, class: "form-select text-muted" %>
              </div>
              <div class="d-flex justify-content-between align-items-center border form-control my-2" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                <a class="text-dark" style="text-decoration: none;">Advanced Settings</a>
                <i class="fa-solid fa-chevron-down"></i>
              </div>
              <div class="collapse" id="collapseExample">
                <div class="card card-body">
                  <div class="form-check form-switch">
                    <%= form.check_box :allow_comments, class: "form-check-input", role: "switch", checked: true %>
                    <%= form.label :allow_comments, style: "display: block", class: "form-check-label" %>
                  </div>
                  <div class="form-check form-switch">
                    <%= form.check_box :show_likes_count, class: "form-check-input", role: "switch", checked: true %>
                    <%= form.label :show_likes_count, style: "display: block", class: "form-check-label" %>
                  </div>
                </div>
              </div>
            </div>
            <div  style="width: 50%;">
              <%= form.file_field :images, multiple: true, id: "recipe-images", required: true %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= form.submit "Create Recipe", class: "btn btn-orange" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_liker.html.erb
<div class="d-flex justify-content-between">
  <div class="d-flex">
    <%= image_tag liker.profile_pic.attached? ? liker.profile_pic : 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 2.5rem" %>
    <div class="d-flex flex-column mx-3 justify-content-center">
      <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:10rem">
        <%= link_to liker, class:  "a-decoration-none", data: {turbo: 'false'} do %>
          <%= (liker.username).capitalize %>
        <% end %>
      </small>
    </div>
  </div>
  <%= render 'layouts/shared/follow_state', user: liker %>
</div>

app/views/recipes/_modal_comment.html.erb
<div id="recipe<%=comment.recipe_id%>ModalComment<%=comment.id%>">
  <div class="d-flex justify-content-between">
    <div class="d-flex">
     <%= image_tag comment.user.profile_pic.attached? ? comment.user.profile_pic : 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 2.5rem; max-height:2.5rem" %>
      <div class="d-flex flex-column mx-3 justify-content-center">
        <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:10rem"><%= link_to comment.user, class:  "a-decoration-none", data: {turbo: 'false'} do %><%= (comment.user.username).capitalize %><% end %></small>
        <small > <%= comment.body %> </small>
        <small class="text-muted" > <%=  time_ago_in_words(comment.created_at)  %> </small>
      </div>
    </div>
    <% if comment.user == current_user%>
      <%= button_to comment_path(id: comment.id), method: :delete, style: "background:none; border:none " do %>
        <i class="fa fa-times"> </i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<div class="my-3" id="<%= dom_id recipe %>">
  <div class="card" style="width: 25rem;">
    <div class="card-header bg-white">
      <div class="d-flex justify-content-between">
        <div>
          <%= link_to recipe.user, class:  "a-decoration-none" do %>
            <% if recipe.user.profile_pic.attached? %>
              <% image_tag recipe.user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 10%" %>
            <% else %>
              <% image_tag 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 10%" %>
            <% end %>
          <% end %>
          <%= link_to recipe.user, class:  "a-decoration-none" do %>
            <span class="fw-bold mx-2 ">
              <%= (recipe.user.username).capitalize %>
            </span>
          <% end %>
        </div>
        <div>
          <div class="dropdown">
            <a class="text-dark fs-4" style="text-decoration:none" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              ...
            </a>
            <ul class="dropdown-menu">
              <% if can? :edit, recipe %>
                <li>
                  <%= link_to '#', class: 'dropdown-item', data: { bs_toggle: 'modal', bs_target: "#staticBackdropEdit" } do %>
                    Edit recipe
                  <% end %>
                </li>
              <% end %>
              <% if can? :destroy, recipe %>
                <li>
                  <%= button_to 'Delete recipe', recipe, method: :delete, class: "dropdown-item" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div id="recipe<%= recipe.id %>_images" class="carousel slide" data-bs-ride="true">
        <div class="carousel-inner">
          <% recipe.images.each_with_index do |img, i| %>
            <div class="carousel-item <%= i == 0 ? 'active' : '' %>" style="height: 15rem">
              <%= link_to recipe_path(recipe) do %>
                <%= image_tag img, class: "d-block w-100", style: "max-height: 100%; object-fit: cover;" %>
              <% end %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#recipe<%= recipe.id %>_images" data-bs-slide="prev">
          <span class="carousel-control-prev-icon bg-dark rounded-circle " aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#recipe<%= recipe.id %>_images" data-bs-slide="next">
          <span class="carousel-control-next-icon bg-dark rounded-circle " aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
        <div class="carousel-indicators" style="position:static">
          <% recipe.images.each_with_index do |img, i| %>
            <button type="button" data-bs-target="#recipe<%= recipe.id %>_images" data-bs-slide-to="<%= i %>" class=" bg-dark <%= i==0 ?  'active' : '' %>" <%= i==0 ? 'aria-current="true"' : '' %> aria-label="Slide <%= i+1 %>"></button>
          <% end %>
        </div>
      </div>
      <%= render "recipes/recipe_actions", recipe: recipe %>
      <div>
        <% if recipe.category %>
          <%= link_to recipe.category.name, category_path(recipe.category), class: "badge rounded-pill text-bg-warning", style: "text-decoration: none;" %>
        <% end %>
      </div>
      <p class="card-text truncate-text"><span class="fw-bold " ><%= recipe.title %></span> <%= recipe.description %></p>
      <p class="card-text truncate-text"><span class="fw-bold">Preparation steps</span> <%= recipe.preparation_steps %></p>
      <%= render "recipes/recipe_comments", recipe: recipe %>
      <small class="text-muted"><%= time_ago_in_words(recipe.created_at) %></small>
    </div>
    <%= render "recipes/comment_post", recipe: recipe %>
  </div>
</div>
<% if can? :update, Recipe %>
  <%# render partial: 'recipes/form', locals: { recipe: recipe } %>
  <%= render partial: 'recipes/edit_form', locals: { recipe: recipe } %>
<% end %>

app/views/recipes/_recipe_actions.html.erb
<%= turbo_frame_tag "recipe#{recipe.id}actions" do %>
  <div class="d-flex justify-content-start align-items-center gap-1 mb-0">
    <%= button_to toggle_like_path(recipe_id: recipe.id), method: :recipe, style: "border:none; background:none", id: "recipe#{recipe.id}actions-likeBtn" do %>
      <i class="<%= recipe.likes.find_by(user: current_user) ? "fa-solid color-red" : "fa-regular" %> fa-heart fa-xl"></i>
    <% end %>
    <a href="#" data-bs-toggle="modal" data-bs-target="#recipe<%= recipe.id %>_commentsModal" style="text-decoration:none" >
      <i class="fa-regular fa-comment fa-xl fa-flip-horizontal text-dark"> </i>
    </a> 
    <%# if can? :toggle_favorite, recipe %>
      <%# render "recipes/recipe_favorites", recipe: recipe %>
    <%# end %>
    <% if current_user != recipe.user %>
      <%= render "recipes/recipe_favorites", recipe: recipe %>
    <% end %>

  </div>
  <a href="#" data-bs-toggle="modal" data-bs-target="#recipe<%= recipe.id %>_likesModal" style="text-decoration:none" class="text-dark">
    <small class="fw-bold my-1"><%= pluralize(recipe.likes.count, "like") %> </small>
  </a>

  <!-- Modal -->
  <div class="modal fade" id="recipe<%= recipe.id %>_likesModal" tabindex="-1" aria-labelledby="recipe<%= recipe.id %>_likesModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="recipe<%= recipe.id %>_likesModalLabel">Recipe Likes</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="d-flex flex-column gap-3" >
            <% recipe.likers.each do |liker| %>
              <%= render "recipes/liker", liker: liker %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/_recipe_comments.html.erb
<%= turbo_frame_tag "recipe#{recipe.id}comments" do %>
  <% if recipe.comments.count > 0 %>
    <a href="#" data-bs-toggle="modal" data-bs-target="#recipe<%= recipe.id %>_commentsModal" style="text-decoration:none" >
      <small class="text-muted">View all <%= pluralize(recipe.comments.count, "comments") %> </small>
    </a>
  <% end %>
  <% recipe.comments.last(5).each do |comment| %>
    <p class="card-text m-0"> <%= link_to comment.user, class:  "a-decoration-none", data: {turbo: 'false'} do %> <span class="fw-bold"><%= (comment.user.username).capitalize %></span><% end %> <%= comment.body %> </p>
  <% end %>


  <!-- Modal -->
  <div class="modal fade" id="recipe<%= recipe.id %>_commentsModal" tabindex="-1" aria-labelledby="recipe<%= recipe.id %>_commentsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="recipe<%= recipe.id %>_commentsModalLabel">Recipe Comments</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="d-flex flex-column gap-3" >
            <% recipe.comments.each do |comment| %>
              <%= render "recipes/modal_comment", comment: comment %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/_recipe_favorites.html.erb
<%= turbo_frame_tag "recipe#{recipe.id}favorites" do %>
  <div class="d-flex justify-content-start align-items-center gap-1 mb-3 mt-3">
    <%= button_to toggle_favorites_path(recipe_id: recipe.id), method: :recipe, style: "border:none; background:none", id: "recipe#{recipe.id}actions-favoriteBtn" do %>
      <i class="<%= recipe.favorites.find_by(user: current_user) ? 'fas text-orange' : 'far' %> fa-star fa-xl"></i>
    <% end %>
  </div>
<% end %>

app/views/recipes/_recipes.html.erb
<% @recipes.each do |recipe|  %>
  <div class=" col-lg-4 col-md-6 col-sm-12">
    <div class="card" style="width: 23rem;">
      <div class="card-header bg-white">
        <div class="d-flex justify-content-between">
          <div>
            <%= link_to recipe.user, class:  "a-decoration-none" do %>
              <% if recipe.user.profile_pic.attached? %>
                <% image_tag recipe.user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 10%" %>
              <% else %>
                <% image_tag 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 10%" %>
              <% end %>
            <% end %>
            <%= link_to recipe.user, class:  "a-decoration-none" do %>
              <span class="fw-bold mx-2 ">
                <%= (recipe.user.username).capitalize %>
              </span>
            <% end %>
          </div>
          <div>
            <div class="dropdown">
              <a class="text-dark fs-4" style="text-decoration:none" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                ...
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to '#', class: 'dropdown-item', data: { bs_toggle: 'modal', bs_target: '#staticBackdrop' } do %>
                    Edit recipe
                  <% end %>
                </li>
                <li><%= button_to 'Delete recipe', recipe, method: :delete, class:"dropdown-item" %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div id="recipe<%= recipe.id %>_images" class="carousel slide" data-bs-ride="true">
          <div class="carousel-inner">
            <% recipe.images.each_with_index do |img, i| %>
              <div class="carousel-item <%= i == 0 ? 'active' : '' %>" style="height: 15rem">
                <%= link_to recipe_path(recipe) do %>
                  <%= image_tag img, class: "d-block w-100", style: "max-height: 100%; object-fit: cover;" %>
                <% end %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#recipe<%= recipe.id %>_images" data-bs-slide="prev">
            <span class="carousel-control-prev-icon bg-dark rounded-circle " aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#recipe<%= recipe.id %>_images" data-bs-slide="next">
            <span class="carousel-control-next-icon bg-dark rounded-circle " aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
          <div class="carousel-indicators" style="position:static">
            <% recipe.images.each_with_index do |img, i| %>
              <button type="button" data-bs-target="#recipe<%= recipe.id %>_images" data-bs-slide-to="<%= i %>" class=" bg-dark <%= i==0 ?  'active' : '' %>" <%= i==0 ? 'aria-current="true"' : '' %> aria-label="Slide <%= i+1 %>"></button>
            <% end %>
          </div>
        </div>
        <%= render "recipes/recipe_actions", recipe: recipe %>
        <div>
          <% if recipe.category %>
            <%= link_to recipe.category.name, category_path(recipe.category), class: "badge rounded-pill text-bg-warning", style: "text-decoration: none;" %>
          <% end %>
        </div>
        <p class="card-text truncate-text"><span class="fw-bold " ><%= recipe.title %></span> <%= recipe.description %></p>
        <p class="card-text truncate-text"><span class="fw-bold">Preparation steps</span> <%= recipe.preparation_steps %></p>
        <%= render "recipes/recipe_comments", recipe: recipe %>
        <small class="text-muted"><%= time_ago_in_words(recipe.created_at) %></small>
      </div>
      <%= render "recipes/comment_post", recipe: recipe %>
    </div>
  </div>
<% end %>
<%# render partial: 'recipes/form', locals: { recipe: @recipe } %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<div class="d-flex justify-content-center mt-4">
  <%= render partial: "recipe_show", locals: { recipe: @recipe } %>
</div>