config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :categories
  devise_for :users

  resources :users, only: [:show, :index, :destroy] do
    member do
      get :assign_roles
      patch :update_roles
    end
  end

  root "home#index"

  resources :roles
  resources :comments, only: [:create, :destroy]

  post "toggle_like", to:  "likes#toggle_like", as: :toggle_like
  post "toggle_favorite", to:  "favorites#toggle_favorite", as: :toggle_favorites

  post "follow", to: 'follows#follow', as: :follow
  delete 'unfollow', to: 'follows#unfollow', as: :unfollow
  delete 'cancel_request', to: 'follows#cancel_request', as: :cancel_request

  post 'accept_follow', to: 'follows#accept_follow', as: :accept_follow
  delete 'decline_follow', to: 'follows#decline_follow', as: :decline_follow
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :recipes, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_one_attached :profile_pic, dependent: :destroy
 
  has_and_belongs_to_many :roles, join_table: :roles_users

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follow_requests, -> {where(accepted: false) }, class_name: "Follow", foreign_key: "followed_id"
  # followers 
  has_many :accepted_recieved_requests, -> {where(accepted: true) }, class_name: "Follow", foreign_key: "followed_id"
  #  followings
  has_many :accepted_sent_requests, -> {where(accepted: true) }, class_name: "Follow", foreign_key: "follower_id"

  # has_many :recieved_requests, class_name: "Follow", foreign_key: "followed_id"
  # has_many :sent_requeasts, class_name: "Follow", foreign_key: "follower_id"
  
  has_many :waiting_sent_requests, -> {where(accepted: false) }, class_name: "Follow", foreign_key: "follower_id"

  has_many :followers, through: :accepted_recieved_requests, source: :follower
  has_many :followings, through: :accepted_sent_requests, source: :followed
  has_many :waiting_followings, through: :waiting_sent_requests, source: :followed

  # def follow(user)  
  #   # self = me
  #   Follow.create(follower: self, followed: user)
  # end

  after_create :follow_all_users
  # after_create :follow_all_users, if: :admin?


  def follow(user)
    unless self.followings.include?(user)
      Follow.create(follower: self, followed: user)
    end
  end

  def unfollow(user)
    self.accepted_sent_requests.find_by(followed: user)&.destroy
  end

  def cancel_request(user)
    self.waiting_sent_requests.find_by(followed: user)&.destroy
  end
  
  def toggle_role
    if normal?
      admin!
    else
      normal!
    end
  end

  # def follow_all_users
  #   if self.admin
  #     User.where.not(id: self.id).each do |user|
  #       follow(user)
  #     end
  #   end
  # end
  def follow_all_users
    if super_admin?
      User.where.not(id: self.id).each do |user|
        follow(user)
      end
    end
  end

   def super_admin?
    roles.exists?(name: 'Super Admin')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy ]
  # before_action :is_super_admin?, except: [:show]
  load_and_authorize_resource

  def index
    @userss = User.all
    if params[:search_query].present?
      @users = User.where("username LIKE ?", "%#{params[:search_query]}%")
    else
      @users = []
    end

    if turbo_frame_request?
      render partial: "layouts/search_results", locals: {users: @users}
    end
  end

  def show
    @recipes = Recipe.all
  end
  
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def assign_roles
    @user = User.find(params[:id])
    @roles = Role.all
  end


  def update_roles
    @user = User.find(params[:id])
    role_ids = params[:user][:role_ids].reject(&:blank?)

    # if current_user.super_admin?
      @user.roles = Role.where(id: role_ids)
      redirect_to users_path, notice: "Roles successfully updated."
    # else
    #   redirect_to root_path, alert: "You do not have permission to perform this action."
    # end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def is_super_admin?
    redirect_to root_path unless current_user.roles.any? { |role| role.name == 'Super Admin' }
  end
  
end

app/views/users/_profile_header.html.erb
<div class="container border-bottom d-flex justify-content-center align-items-center gap-5", style="min-height: 20rem">
  <%= image_tag user.profile_pic.attached? ? user.profile_pic : 'user-pp.png', class: "img-thumbnail rounded-circle w-25", style: "max-width: 8rem; max-height:8rem" %>

  <div class="w-50 d-flex flex-column gap-4">
    <div class="d-flex gap-3 align-items-center">
      <p class="m-0 fw-bold"><%= (user.username).capitalize %></p>
      <%# <button class="btn border border-1"> Message </button> %>
      <%= render 'layouts/shared/follow_state', user: user %>
      <% if user == current_user %>
        <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-transparent border"%>
      <% end %>
    </div>

    <div class="d-flex gap-5">
      <small class="fw-bold"><%= pluralize(user.recipes.count, "Post") %></small>
      <small class="fw-bold"><%= pluralize(user.followers.count, "Follower") %></small>
      <small class="fw-bold"><%= pluralize(user.followings.count, "Following") %></small>
    </div>

    <div class="d-flex flex-column">
      <small class="fw-bold"><%= user.full_name%></small>
      <small><%= user.bio%></small>
    </div>
  </div>
</div>

app/views/users/_profile_posts.html.erb
<div class="container d-flex flex-column">
  <ul class="nav nav-tabs d-flex justify-content-center align-items-center" id="myTabs" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="tab1" data-bs-toggle="tab" data-bs-target="#content1" type="button" role="tab" aria-controls="content1" aria-selected="true">
        <div class="w-content ">
          <i class="fa-solid fa-table-cells"> </i>
          <small>POSTS</small>
        </div>
      </button>
    </li>
    <% if current_user == user %>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="tab2" data-bs-toggle="tab" data-bs-target="#content2" type="button" role="tab" aria-controls="content2" aria-selected="false">
        <div class="w-content">
          <i class="fa-solid fa-star"> </i>
          <small>FAVORITES</small>
        </div>
      </button>
    </li>
    <% end %>
  </ul>
  <div class="tab-content row justify-content-center align-items-center" id="myTabContent">
    <div class="tab-pane fade show active" id="content1" role="tabpanel" aria-labelledby="tab1">
      <div class="row">
        <% user.recipes.each do |recipe| %>
          <div class="col-lg-4 col-md-6 col-sm-12 p-3 mb-4 profile-post" style="height:20rem;position:relative">
            <%= link_to recipe do %>
              <%= image_tag recipe.images.first, class: "img-thumbnail", style: "width:100%;height:20rem;object-fit:cover" %>
              <div class="d-flex align-items-center justify-content-center gap-1 w-100 profile-post-likes">
                <i class="fa-solid fa-heart fa-xl text-white"> </i>
                <small class="text-white fw-bold"><%= recipe.likes.count %> </small>
                <i class="fa-solid fa-comment fa-xl fa-flip-horizontal text-white"> </i>
                <small class="text-white fw-bold"><%= recipe.comments.count %> </small>
              </div>
              <% if recipe.images.count > 1 %>
                <i class="fa-solid fa-images text-white multiple-images"> </i>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade show" id="content2" role="tabpanel" aria-labelledby="tab2">
      <div class="row">
        <% @recipes.each do |recipe| %>
          <% if recipe.favorites.exists?(user: user) || recipe.likes.exists?(user: user) %>
            <div class="col-lg-4 col-md-6 col-sm-12 p-3 mb-4 profile-post" style="height:20rem;position:relative">
              <%= link_to recipe do %>
                <%= image_tag recipe.images.first, class: "img-thumbnail", style: "width:100%;height:20rem;object-fit:cover" %>
                <div class="d-flex align-items-center justify-content-center gap-1 w-100 profile-post-likes">
                  <i class="fa-solid fa-heart fa-xl text-white"> </i>
                  <small class="text-white fw-bold"><%= recipe.likes.count %> </small>
                  <i class="fa-solid fa-comment fa-xl fa-flip-horizontal text-white"> </i>
                  <small class="text-white fw-bold"><%= recipe.comments.count %> </small>
                </div>
                <% if recipe.images.count > 1 %>
                  <i class="fa-solid fa-images text-white multiple-images"> </i>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_profile_private.html.erb
<div class="container bg-white border text-center p-5">
  <p>This account is private </p>
  <p> Follow this account to see their photos </p>
<div>

app/views/users/_switch_role.html.erb
<%= turbo_frame_tag "switch#{user.id}role" do %>
  <%# if user.role != 'admin' %>
    <%= link_to switch_role_user_path(user),  method: :get, title: "Switch to Normal User" do %>
      <i class="fas fa-exchange-alt"></i>
    <% end %>
 <%# else %>
  <%= link_to switch_role_user_path(user),  method: :get, title: "Switch to Admin User" do %>
    <i class="fas fa-exchange-alt"></i>
  <% end %>
 <%# end %>
<% end %>

app/views/users/assign_roles.html.erb
<div class="container mt-5">
  <div class="card mx-auto" style="max-width: 700px;">
    <div class="card-header">
      <h3>Assign Roles to <%= (@user.username).capitalize %></h3>
    </div>
    <%= form_with(model: @user, url: update_roles_user_path(@user), method: :patch) do |f| %>
      <div class="card-body">
        <div class="form-check mb-3">
          <% @roles.each do |role| %>
            <label class="form-check-label d-block">
              <%= check_box_tag 'user[role_ids][]', role.id, @user.roles.include?(role), class: "form-check-input" %>
              <%= role.name.capitalize %>
            </label>
          <% end %>
        </div>
      </div>
      <div class="card-footer d-flex">
        <%= f.submit "Update Roles", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container" style="width: 75rem; margin-top: 6rem;">
  <table class="table table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>User Name</th>
        <th>Email</th>
        <th>Created Recipes</th>
        <th>Role</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @userss.each do |user| %>
        <tr>
          <td>
            <% if user && user.profile_pic.attached? %>
              <%= image_tag user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 2rem" %>
            <% else %>
              <%= image_tag 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 2rem" %>
            <% end %>
            <%= user.username %>
          </td>
          <td><%= user.email %></td>
          <td>
            <%= link_to pluralize(user.recipes.count, "recipes"), user_path(user), style: "text-decoration: none;" %>
          </td>
          <td>
            <% user.roles.each do |role| %>
              <%= role.name.capitalize %>
              <% unless role == user.roles.last %>
                ,
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to assign_roles_user_path(user), method: :patch do %>
              <i class="fas fa-user-cog text-primary"></i>
            <% end %>
            <%= link_to user_path(user), method: :delete, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to delete this user?" } do %>
              <i class="fas fa-trash text-danger"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render 'users/profile_header', user: @user %>
<% if !@user.private || @user == current_user || current_user.followings.include?(@user) %>
  <%= render 'users/profile_posts', user: @user %>
<% else %>
  <%= render 'users/profile_private' %>
<% end%>