config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :categories
  devise_for :users

  resources :users, only: [:show, :index, :destroy] do
    member do
      get :assign_roles
      patch :update_roles
    end
  end

  root "home#index"

  resources :roles
  resources :comments, only: [:create, :destroy]

  post "toggle_like", to:  "likes#toggle_like", as: :toggle_like
  post "toggle_favorite", to:  "favorites#toggle_favorite", as: :toggle_favorites

  post "follow", to: 'follows#follow', as: :follow
  delete 'unfollow', to: 'follows#unfollow', as: :unfollow
  delete 'cancel_request', to: 'follows#cancel_request', as: :cancel_request

  post 'accept_follow', to: 'follows#accept_follow', as: :accept_follow
  delete 'decline_follow', to: 'follows#decline_follow', as: :decline_follow
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :recipes, dependent: :destroy
  validates :name, presence: true, uniqueness: true,  length: { minimum: 3, maximum: 25 }
  validates :description,  length: {minimum: 6, maximum: 100}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  def index
    @categories = Category.all
    @category = Category.new
  end

  def show
    @recipes = @category.recipes
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { redirect_to root_url, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description, :user_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories.html.erb
<%# turbo_frame_tag "categories" do %>
  <% @categories.each do |category| %>
    <tr>
      <th>
        <%= link_to category do %>
          <%= link_to category.name, category_path(category), class: "badge rounded-pill text-bg-warning", style: "text-decoration: none;" %>
        <% end %>
      </th>
      <td><%= pluralize(category.recipes.count, "recipes")  %></td>
      <% if can? :manage, Category %>
        <td>
          <div class="d-flex">
            <%= link_to '#', class: 'me-2',  data: { bs_toggle: 'modal', bs_target: "#staticBackdropEdit" } do %>
              <i class="fas fa-edit text-primary"></i>
            <% end %>
            <%= link_to category_path(category), method: :delete, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to delete this category?" } do %>
              <i class="fas fa-trash text-danger"></i>
            <% end %>
          </div>
        </td>
      <% end %>
    </tr>
  <% end %>
  <%# end %>
  <%= render partial: 'categories/edit_form', locals: { category: @category } %>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= category.user_id %>
  </p>

</div>

app/views/categories/_edit_form.html.erb
<div class="modal fade modal-lg" id="staticBackdropEdit<%= category.id %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <%= form_with(model: category, local: true) do |form| %>
      <div class="modal-content" style="width: 70%; margin-left: 20%;">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Edit Category</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div>
            <% if @category.errors.any? %>
              <div style="color: red;">
                <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
                <ul>
                  <% @category.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="my-2">
              <% if current_user.profile_pic.attached? %>
                <%= image_tag current_user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 8%" %>
              <% else %>
                <%= image_tag 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 8%" %>
              <% end %>
              <span class="fw-bold mx-2"><%= (current_user.username).capitalize %></span>
            </div>
            <div class="my-2">
              <%= form.text_field :name, placeholder: "Write a category name...", class: "form-control" %>
            </div>
            <div class="my-2">
              <%= form.text_area :description, placeholder: "Add description", class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= form.submit "Update category", class: "btn btn-orange" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<!-- Modal -->
<%# turbo_frame_tag "new_category", src: new_category_path, target: "_top" %>
<div class="modal fade modal-lg" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <%= form_with(model: category) do |form| %>
      <%# render "layouts/flash_messages" %>
      <div class="modal-content" style="width: 70%; margin-left: 20%;">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Create New Category</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div>
            <% if category.errors.any? %>
              <div style="color: red;">
                <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
                <ul>
                  <% category.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="my-2">
              <% if current_user.profile_pic.attached? %>
                <%= image_tag current_user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 8%" %>
              <% else %>
                <%= image_tag 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 8%" %>
              <% end %>
              <span class="fw-bold mx-2"><%= (current_user.username).capitalize %></span>
            </div>
            <div class="my-2">
              <%= form.text_field :name, placeholder: "Write a category name...", class: "form-control" %>
            </div>
            <div class="my-2">
              <%= form.text_area :description, placeholder: "Add description", class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= form.submit "Create category", class: "btn btn-orange" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row mt-5 mb-2">
    <div class="col">
      <h3>Category list</h3>
    </div>
    <% if can? :manage, Category %>
      <div class="col text-end" type="button" class="text-dark" data-bs-toggle="modal" data-bs-target="#staticBackdropcat">
        <button class="btn btn-warning">New Category</button>
      </div>
    <% end %>
  </div>
  <table class="table table-bordered table-hover">
    <thead class="table-dark ">
      <tr>
        <th scope="col">Category Name</th>
        <th scope="col">Recipes</th>
        <% if can? :manage, Category %>
          <th>Action</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%# render "categories/categories", categories: @categories %>
      <% @categories.each do |category| %>
        <tr>
          <th>
            <%= link_to category do %>
              <%= link_to category.name, category_path(category), class: "badge rounded-pill text-bg-warning", style: "text-decoration: none;" %>
            <% end %>
          </th>
          <td><%= pluralize(category.recipes.count, "recipes")  %></td>
          <% if can? :manage, Category %>
            <td>
              <div class="d-flex">
                <%= link_to '#', class: 'me-2',  data: { bs_toggle: 'modal', bs_target: "#staticBackdropEdit#{category.id}" } do %>
                  <i class="fas fa-edit text-primary"></i>
                <% end %>
                <%= link_to category_path(category), method: :delete, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to delete this category?" } do %>
                  <i class="fas fa-trash text-danger"></i>
                <% end %>
              </div>
            </td>
          <% end %>
        </tr>
        <%= render partial: 'categories/edit_form', locals: { category: category } %>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'categories/form', category: @category %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-12">
      <h3 class="text-center decorated-heading">List of Recipes Available In This Category</h3>
      <hr>
    </div>
  </div>
  <div class="row">
    <%= render 'recipes/recipes' %>
  </div>
</div>